### PR TITLE
Vert.X3 3.1.0 and Kotlin 1.0 beta2

### PR DESCRIPTION
**Pull request by windoze**
Also bump version to 0.0.10

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
@windoze thanks, will release immediately :)

**Comment by cy6erGn0m** [comment]
See 0.0.10

**Comment by windoze** [comment]
Thanks!
Also I'm thinking about to add a wrapper for Vert.X3 Web Router, instead of using another incompatible implementation.

**Comment by cy6erGn0m** [comment]
@windoze feel free to contribute. Currently I haven't enough time to develop it

**Pull request merged**
